### ISSUE TITLE
Colab notebook: ValueError (due to newer TF version in Colab)

### ISSUE THREAD

**Issue by jinxsfe** [leeroyhannover/DeBCR#1]
Hi , I am trying to using the colabnotebook to run the code part , but encounter that issue
<img width="1199" alt="Screenshot 2024-09-09 at 4 26 56 PM" src="https://github.com/user-attachments/assets/22c1887b-a55e-4ba9-bf8e-b06a8a1b16c8">
can you give me some sign for which part should I add it to?

**Comment by jinxsfe** [comment]
@ArtsemiY @leeroyhannover

**Comment by ArtsemiY** [comment]
Hello @jinxsfe !
It may be due to the differences in the TensorFlow versions (we used v2.11, while v2.17 is current Colab default). Please reinstall tensorflow-v.2.17 to tensorflow-gpu-v.2.11 in Colab by running the following code:
`! pip install tensorflow-gpu==2.11`
It will ask to restart runtime, please do so and re-run the code cells from beginning. Let us know how it goes
